$env:SERVER_PORT = "8080"

$env:MYSQL_DRIVER = "com.mysql.cj.jdbc.Driver"
$env:MYSQL_URL = "jdbc:mysql://192.168.150.101:3306/ai_rag?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
$env:MYSQL_USERNAME = "root"
$env:MYSQL_PASSWORD = "123"

$env:PGVECTOR_DRIVER = "org.postgresql.Driver"
$env:PGVECTOR_URL = "jdbc:postgresql://192.168.150.101:5432/ai_rag_vector"
$env:PGVECTOR_USERNAME = "postgres"
$env:PGVECTOR_PASSWORD = "123456"

$env:RABBITMQ_HOST = "192.168.150.101"
$env:RABBITMQ_PORT = "5672"
$env:RABBITMQ_USERNAME = "tjxt"
$env:RABBITMQ_PASSWORD = "123321"
$env:RABBITMQ_VHOST = "/tjxt"

$env:DASHSCOPE_API_KEY = "sk-de85666bd13845b99a9eeca7db6cfce0"
$env:DASHSCOPE_CHAT_MODEL = "qwen-turbo"
$env:DASHSCOPE_STREAMING_MODEL = "qwen-turbo"
$env:DASHSCOPE_EMBEDDING_MODEL = "text-embedding-v2"
$env:DASHSCOPE_CHAT_TEMPERATURE = "0.3"
$env:DASHSCOPE_CHAT_MAX_TOKENS = "2048"

$env:RAG_HISTORY_LIMIT = "10"
$env:RAG_RETRIEVAL_TOP_K = "5"
$env:RAG_MAX_SEGMENT_SIZE = "500"
$env:RAG_MAX_OVERLAP_SIZE = "100"
$env:RAG_RETRIEVAL_MAX_RESULTS = "5"
$env:RAG_MIN_SCORE = "0.3"
$env:RAG_EMBEDDING_DIMENSION = "1536"
$env:RAG_UPLOAD_DIR = "data/uploads"
$env:RAG_KNOWLEDGE_ASYNC_EXCHANGE = "rag.knowledge.exchange"
$env:RAG_KNOWLEDGE_ASYNC_QUEUE = "rag.knowledge.document.process"
$env:RAG_KNOWLEDGE_ASYNC_ROUTING_KEY = "rag.knowledge.document.process"

$env:JWT_SECRET = "n7K!4xQ2mL9@cV6#pR8sT1wZ5yH3uJ0bD4fN7qE2kM9aX6vP"
$env:JWT_EXPIRATION_SECONDS = "7200"
